
# CAN Bus Items
DRIVE_RIGHT_FRONT = 3
DRIVE_RIGHT_BACK = 2

DRIVE_LEFT_FRONT = 4
DRIVE_LEFT_BACK = 1

SHOOTER = 0
INTAKE_SPIN = 6
INTAKE_UPPER = 9

#PWM Items
SHOOTER_SERVO = 0
SERVO_MIN = 40
SERVO_MAX = SERVO_MIN + 105

#DIO Items
INTAKE_BOTTOM_LIMIT = 0
INTAKE_TOP_LIMIT = 1

#Controller ports (THESE ARE TO BE CHANGED MID GAME)
ROTARY_CONTROLLER = 0
OPERATOR_CONTROLLER = 1

